theme:
    line: +==~~~~~====~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+
    line2: ------------------------------------------------------------------------------
    line_colors: [ 'c', 'b', 'm', 'r' ]