theme:
    # Note:  line1 through line4 have shortcuts defined in the formatter %l1 - %l4
    # However you can define any extra lines you wish.
    line1: %x!+==~~~~~====~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+%xn
    line2: %x!+==~~~~~====~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+%xn
    line3: %x!%~%r----[AresMUSH]----------------------------------------------------------------%xn
    line4: %x!------------------------------------------------------------------------------%r%~%xn
    mush_name: AresMUSH
